project:
  type: website
  output-dir: docs
  resources:
    - google3ce7468ddf2c501f.html

website:
  site-url: https://brookepryan.github.io
  favicon: media/frawg.png
  navbar:
    title: "Brooke P. Ryan"
    left:
      - href: index.qmd
        text: Home
      - href: environmental_experience.qmd
        text: Research
      - href: spanish.qmd
        text: Spanish
      - href: sewing_blog.qmd
        text: Sewing and Design
      - href: bug_blog.qmd
        text: Invertebrates
        

format:
  html:
    theme: styles.scss
    light: minty
    dark: superhero
    mainfont: "Quicksand"
    toc: true
    page-layout: full
