project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Brooke Ryan"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: environmental_experience.qmd
        text: Environmental Experience
      - href: sewing_blog.qmd
        text: Sewing!
        

format:
  html:
    theme:
      light: minty
      dark: superhero
    css: styles.css
    toc: true
    page-layout: full

editor: visual

