project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Brooke Ryan"
    left:
      - href: index.qmd
        text: Home
      - href: environmental_experience.qmd
        text: Environmental Experience
      - href: spanish.qmd
        text: Spanish Development
      - href: sewing_blog.qmd
        text: Sewing!
        

format:
  html:
    theme: styles.scss
    light: minty
    dark: superhero
    mainfont: "Quicksand"
    toc: true
    page-layout: full


