project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Brooke Ryan"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - environmental.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

